.catalog:
  name: "mattermost"
  version: "4.6.1"
  description: "Mattermost is an open source, self-hosted Slack-alternative."
  questions:
      - variable: "mattermost_db_login"
        description: "Mattermost database login"
        label: "Database login"
        type: "string"
        required: true
        default: "mattermost"
      - variable: "mattermost_db_password"
        description: "Mattermost database password"
        label: "Database password"
        type: "password"
        required: true
        default: "mattermost_password"
      - variable: "mattermost_db_name"
        description: "Mattermost database name"
        label: "Database name"
        type: "string"
        required: true
        default: "mattermost"
      - variable: "mattermost_db_driver"
        description: "Mattermost database driver"
        label: "Database Driver"
        type: "string"
        required: true
        default: "mysql"
      - variable: "mattermost_port"
        description: "Mattermost port"
        label: "Mattermost port"
        type: "string"
        required: true
        default: "80"
      - variable: "databasehost_link"
        description: |
          stack/service link or external service link to postgres.
        label: "Postgres stack/service"
        default: "postgresql/postgresql-master"
        required: true
        type: "service"
mattermost:
  scale: 1
